name: navi
description: A time scheduling app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  string_to_color: ^2.0.0

  timeline_tile:
    git:
      url: https://github.com/JHBitencourt/timeline_tile.git
  flex_color_picker: ^3.2.1
  intl: ^0.18.1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
