// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY2brusMpKUUJbFgwGHWpSdNZHe36dbUI',
    appId: '1:469701934291:android:3ed2b19c6bbeef57e6e826',
    messagingSenderId: '469701934291',
    projectId: 'navi-11b61',
    databaseURL: 'https://navi-11b61-default-rtdb.firebaseio.com',
    storageBucket: 'navi-11b61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChPV7RIRf6rSCRVIn0QUhMLArlZRGgdMw',
    appId: '1:469701934291:ios:6f1c4823a5bd7262e6e826',
    messagingSenderId: '469701934291',
    projectId: 'navi-11b61',
    databaseURL: 'https://navi-11b61-default-rtdb.firebaseio.com',
    storageBucket: 'navi-11b61.appspot.com',
    androidClientId: '469701934291-ju1efe384cb7chafsk280g0prnbh8bl7.apps.googleusercontent.com',
    iosClientId: '469701934291-03tjtt2r5ru44rnvbfvv58pvmke30r75.apps.googleusercontent.com',
    iosBundleId: 'com.navi.navi',
  );
}
